# Multi-Service / Microservice (API Gateway etc.)

# When to use
# Microservices
# Docker Compose
# API Gateway / Auth / User Service

FROM node:20-alpine

WORKDIR /service

COPY package*.json ./

RUN npm ci

COPY . .

ENV PORT=3005

EXPOSE 3005

CMD ["npm", "start"]
